# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContacts',
            new_name='UserContact',
        ),
    ]
