# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200608_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaminfo',
            name='contact',
        ),
        migrations.AddField(
            model_name='spaminfo',
            name='spam_number',
            field=models.CharField(default=0, max_length=15, unique=True, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
