# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200608_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaminfo',
            name='spam_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
